### ISSUE TITLE
the last application is old and has no nce.

### ISSUE THREAD

**Issue by xandoofc** [holaimscott/yuzu-a10-archive-old#1]
please fix it

**Comment by holaimscott** [comment]
Thanks! We are checking to see what happened. On my end, the APK showed other changes done in the v136 release, but the NCE option disappeared completely.

**Comment by holaimscott** [comment]
Issue has been solved, a new APK has been built and tested <3
https://github.com/holaimscott/yuzu-a10-archive/releases/tag/yuzu-a10-138
